// Thai language labels for the application
export const THAI_LABELS = {
  // Authentication
  login: 'เข้าสู่ระบบ',
  logout: 'ออกจากระบบ',
  email: 'อีเมล',
  password: 'รหัสผ่าน',
  forgotPassword: 'ลืมรหัสผ่าน',
  resetPassword: 'รีเซ็ตรหัสผ่าน',
  rememberMe: 'จดจำการเข้าสู่ระบบ',
  
  // Common actions
  submit: 'ส่ง',
  cancel: 'ยกเลิก',
  confirm: 'ยืนยัน',
  save: 'บันทึก',
  edit: 'แก้ไข',
  delete: 'ลบ',
  add: 'เพิ่ม',
  create: 'สร้าง',
  update: 'อัปเดต',
  search: 'ค้นหา',
  filter: 'กรอง',
  clear: 'ล้าง',
  reset: 'รีเซ็ต',
  back: 'กลับ',
  next: 'ถัดไป',
  previous: 'ก่อนหน้า',
  close: 'ปิด',
  
  // Navigation
  dashboard: 'แดชบอร์ด',
  inventory: 'รายการสินค้าในสต็อก',
  requisitions: 'เบิกสินค้า',
  createRequisition: 'สร้างใบเบิกสินค้า',
  requisitionHistory: 'ประวัติการเบิกสินค้า',
  adminPanel: 'ผู้ดูแลระบบ',
  approvals: 'อนุมัติการเบิก',
  approvalQueue: 'คิวการอนุมัติ',
  products: 'จัดการสินค้า',
  stockAdjustments: 'ปรับปรุงสต็อก',
  notices: 'ประกาศ',
  reports: 'รายงาน',
  import: 'นำเข้าข้อมูล',
  
  // Inventory
  productCode: 'รหัสสินค้า',
  productName: 'ชื่อสินค้า',
  description: 'รายละเอียด',
  category: 'หมวดหมู่',
  unit: 'หน่วย',
  quantity: 'จำนวน',
  remaining: 'คงเหลือ',
  minimumStock: 'สต็อกขั้นต่ำ',
  currentStock: 'สต็อกปัจจุบัน',
  inStock: 'มีสินค้า',
  lowStock: 'สินค้าใกล้หมด',
  outOfStock: 'สินค้าหมด',
  
  // Requisitions
  requisition: 'ใบเบิกสินค้า',
  documentNumber: 'เลขที่เอกสาร',
  requestDate: 'วันที่ขอเบิก',
  status: 'สถานะ',
  draft: 'ร่าง',
  pending: 'รอการอนุมัติ',
  approved: 'อนุมัติแล้ว',
  rejected: 'ปฏิเสธ',
  issued: 'จ่ายแล้ว',
  notes: 'หมายเหตุ',
  reason: 'เหตุผล',
  
  // Actions
  approve: 'อนุมัติ',
  reject: 'ปฏิเสธ',
  issue: 'จ่ายสินค้า',
  export: 'ส่งออก',
  print: 'พิมพ์',
  
  // User info
  name: 'ชื่อ',
  department: 'แผนก',
  role: 'บทบาท',
  user: 'ผู้ใช้',
  admin: 'ผู้ดูแลระบบ',
  
  // Dates and time
  date: 'วันที่',
  time: 'เวลา',
  createdAt: 'สร้างเมื่อ',
  updatedAt: 'อัปเดตเมื่อ',
  
  // Messages
  loading: 'กำลังโหลด...',
  noData: 'ไม่มีข้อมูล',
  success: 'สำเร็จ',
  error: 'เกิดข้อผิดพลาด',
  warning: 'คำเตือน',
  info: 'ข้อมูล',
  
  // Validation messages
  required: 'กรุณากรอกข้อมูล',
  invalidEmail: 'รูปแบบอีเมลไม่ถูกต้อง',
  passwordTooShort: 'รหัสผ่านต้องมีอย่างน้อย 6 ตัวอักษร',
  passwordMismatch: 'รหัสผ่านไม่ตรงกัน',
  invalidCredentials: 'อีเมลหรือรหัสผ่านไม่ถูกต้อง',
  accountDisabled: 'บัญชีผู้ใช้ถูกปิดใช้งาน',
  unauthorized: 'ไม่มีสิทธิ์เข้าถึง',
  forbidden: 'ไม่อนุญาตให้เข้าถึง',
  notFound: 'ไม่พบข้อมูล',
  internalError: 'เกิดข้อผิดพลาดภายในระบบ',
  
  // Theme
  lightTheme: 'โหมดสว่าง',
  darkTheme: 'โหมดมืด',
  toggleTheme: 'เปลี่ยนธีม',
  switchToLight: 'เปลี่ยนเป็นโหมดสว่าง',
  switchToDark: 'เปลี่ยนเป็นโหมดมืด',
  
  // Placeholders
  enterEmail: 'กรอกอีเมล',
  enterPassword: 'กรอกรหัสผ่าน',
  searchProducts: 'ค้นหาสินค้า...',
  selectCategory: 'เลือกหมวดหมู่',
  enterNotes: 'กรอกหมายเหตุ...',
  
  // Confirmations
  confirmDelete: 'คุณแน่ใจหรือไม่ที่จะลบรายการนี้?',
  confirmApprove: 'คุณแน่ใจหรือไม่ที่จะอนุมัติการเบิกนี้?',
  confirmReject: 'คุณแน่ใจหรือไม่ที่จะปฏิเสธการเบิกนี้?',
  confirmLogout: 'คุณแน่ใจหรือไม่ที่จะออกจากระบบ?',
  
  // Success messages
  loginSuccess: 'เข้าสู่ระบบสำเร็จ',
  logoutSuccess: 'ออกจากระบบเรียบร้อยแล้ว',
  saveSuccess: 'บันทึกข้อมูลสำเร็จ',
  deleteSuccess: 'ลบข้อมูลสำเร็จ',
  approveSuccess: 'อนุมัติการเบิกสำเร็จ',
  rejectSuccess: 'ปฏิเสธการเบิกสำเร็จ',
  draftSaved: 'บันทึกร่างเรียบร้อยแล้ว',
  requisitionSubmitted: 'ส่งคำขอเบิกสินค้าเรียบร้อยแล้ว',
  
  // Error messages
  loginError: 'เข้าสู่ระบบไม่สำเร็จ',
  saveError: 'บันทึกข้อมูลไม่สำเร็จ',
  deleteError: 'ลบข้อมูลไม่สำเร็จ',
  loadError: 'โหลดข้อมูลไม่สำเร็จ',
  networkError: 'เกิดข้อผิดพลาดในการเชื่อมต่อ',
  quantityMustBePositive: 'จำนวนต้องมากกว่า 0',
  insufficientStock: 'จำนวนที่ขอเกินสต็อกที่มีอยู่',
  selectAtLeastOneItem: 'กรุณาเลือกสินค้าอย่างน้อย 1 รายการ',
  invalidQuantity: 'มีสินค้าที่จำนวนที่ขอเกินสต็อกที่มีอยู่ กรุณาตรวจสอบอีกครั้ง',
  duplicateCode: 'รหัสสินค้านี้มีอยู่แล้ว',
  invalidDateFormat: 'รูปแบบวันที่ไม่ถูกต้อง (DD/MM/YYYY)',
  invalidDate: 'วันที่ไม่ถูกต้อง',
  
  // Forgot password
  forgotPasswordTitle: 'ลืมรหัสผ่าน',
  forgotPasswordDescription: 'กรอกอีเมลของคุณเพื่อรับลิงก์รีเซ็ตรหัสผ่าน',
  sendResetLink: 'ส่งลิงก์รีเซ็ต',
  backToLogin: 'กลับไปหน้าเข้าสู่ระบบ',
  resetLinkSent: 'หากอีเมลนี้มีอยู่ในระบบ เราจะส่งลิงก์รีเซ็ตรหัสผ่านไปให้คุณ',
  
  // Company info
  companyName: 'ระบบเบิกสินค้าคลังสินค้า',
  welcomeMessage: 'ยินดีต้อนรับสู่ระบบเบิกสินค้า',
  loginSubtitle: 'กรุณาเข้าสู่ระบบเพื่อใช้งาน',
  
  // Additional UI labels
  allCategories: 'ทุกหมวดหมู่',
  allStatuses: 'ทุกสถานะ',
  allItems: 'รายการทั้งหมด',
  noImage: 'ไม่มีรูป',
  select: 'เลือก',
  saveDraft: 'บันทึกร่าง',
  submitRequest: 'ส่งคำขอ',
  submitting: 'กำลังส่ง...',
  addProduct: 'เพิ่มสินค้า',
  addNewProduct: 'เพิ่มสินค้าใหม่',
  editProduct: 'แก้ไขสินค้า',
  selectProduct: 'เลือกสินค้า',
  selectedItems: 'รายการที่เลือก',
  noItems: 'ไม่มีรายการ',
  noItemsYet: 'ยังไม่มีรายการสินค้า กรุณาเพิ่มสินค้าที่ต้องการเบิก',
  productList: 'รายการสินค้า',
  addItem: 'เพิ่มสินค้า',
  removeItem: 'ลบ',
  active: 'เปิดใช้',
  inactive: 'ปิดใช้',
  enable: 'เปิดใช้',
  disable: 'ปิดใช้',
  management: 'การจัดการ',
  viewDetails: 'ดูรายละเอียด',
  exportPDF: 'ส่งออก PDF',
  uploadFile: 'อัปโหลดไฟล์',
  warehouseNotice: 'ประกาศจากคลังสินค้า',
  stockStatus: 'สถานะสต็อก',
  createdBy: 'สร้างโดย',
  approvedBy: 'อนุมัติโดย',
  approvalDate: 'วันที่อนุมัติ',
  issueDate: 'วันที่จ่าย',
  requestedQuantity: 'จำนวนที่ขอ',
  availableStock: 'สต็อกที่มี',
  imageUrl: 'URL รูปภาพ',
  optional: 'ไม่บังคับ',
  helperImageUrl: 'ใส่ URL ของรูปภาพสินค้า หรือเว้นว่างไว้',
  searchPlaceholder: 'ค้นหา...',
  searchProductsPlaceholder: 'ค้นหาสินค้า...',
  selectOrTypeNew: 'เลือกหรือพิมพ์หมวดหมู่ใหม่',
  noMatchingProducts: 'ไม่พบสินค้าที่ตรงกับเงื่อนไขการค้นหา',
  noProductsWithStock: 'ไม่พบสินค้าที่มีสต็อก',
  totalItems: 'รายการทั้งหมด',
  items: 'รายการ',
  viewInventoryDescription: 'ดูรายการสินค้าในสต็อกและสถานะความพร้อมใช้งาน',
  createNewRequisition: 'สร้างใบเบิกสินค้าใหม่',
  manageProductsDescription: 'จัดการข้อมูลสินค้าในระบบ',
} as const;

export type ThaiLabelKey = keyof typeof THAI_LABELS;